shell.run("rom/programs/http/wget", "https://github.com/tyty0817/test/raw/main/Heartaches1.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "Heartaches1.dfpwm")
shell.run("rom/programs/delete", "Heartaches1.dfpwm")
shell.run("rom/programs/http/wget", "https://github.com/tyty0817/test/raw/main/Heartaches2.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "Heartaches2.dfpwm")
shell.run("rom/programs/delete", "Heartaches2.dfpwm")
