shell.run("rom/programs/http/wget", "https://github.com/tyty0817/test/raw/main/shadow1.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "shadow1.dfpwm")
shell.run("rom/programs/delete", "shadow1.dfpwm")
shell.run("rom/programs/http/wget", "https://github.com/tyty0817/test/raw/main/shadow2.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "shadow2.dfpwm")
shell.run("rom/programs/delete", "shadow2.dfpwm")
