shell.run("rom/programs/http/wget", "https://github.com/tyty0817/Minecraft-CC-Music/raw/refs/heads/main/songs/stars1.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "stars1.dfpwm")
shell.run("rom/programs/delete", "stars1.dfpwm")
shell.run("rom/programs/http/wget", "https://github.com/tyty0817/Minecraft-CC-Music/raw/refs/heads/main/songs/stars2.dfpwm")
shell.run("rom/programs/fun/speaker", "play", "stars2.dfpwm")
shell.run("rom/programs/delete", "stars2.dfpwm")